global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Text;
global using ZgradaLibrary.Entiteti;
global using ZgradaLibrary.DTOs;
global using NHibernate;
global using static ZgradaLibrary.Extensions;
global using System.Diagnostics.CodeAnalysis;